<?php
$this->headTitle($this->page->GetTitle());
$this->headMeta()->appendName('keywords', $this->page->GetKeywords());
$this->headMeta()->appendName('description', $this->page->GetDescription() );

$seo=unserialize($this->page->getSeo_options());
if (!empty($seo["robots"])){
    //запретить индексирование
    $this->headMeta()->appendName('robots', $seo["robots"] );
}
if (!empty($seo["canonical"])){
    //указать канонический адрес страницы
    $this->headLink(['rel' => 'canonical', 'href' =>rtrim($this->ServerDefaultUri,"/")."/". $seo["canonical"]]);
}

echo $this->page->GetContent();
//передать в макет имя локали, для мультиязычных сайтов
$this->layout()->locale=$this->locale;

if ($this->getHelperPluginManager()->has("SearchIndex")){
    //поисковый индекс, если есть поисковый плагин-индексатор
    $this->SearchIndex(
        $this->page->GetContent(),
        $this->page->GetTitle(),
        $this->url("page_".$this->locale,["page"=>$this->page->getUrl()]),
        ["material_type"=>"","date_public"=>""]
    );
}
